apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-sbdfcutz
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-sbdfcutz:2da895df9b8ca57979947c87e767497ec1a71104@sha256:ca411769f6c5717b87e91a64e425770214ba05b00ec4c34d5f197165b20d53a3
          name: container-image
